package com.pi.coding.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Session entry recording a branch summary.
 *
 * <p>When navigating away from a branch in the session tree, a summary is
 * generated to preserve context. This allows returning to the branch later
 * with an understanding of what was discussed.
 *
 * <p><b>Validates: Requirement 1.7</b>
 *
 * @param <T>       Type of extension-specific details
 * @param type      Always "branch_summary"
 * @param id        Unique entry identifier
 * @param parentId  Parent entry ID (null for first entry)
 * @param timestamp ISO 8601 timestamp
 * @param fromId    ID of the entry where the branch started
 * @param summary   The generated summary of the branch
 * @param details   Extension-specific data (nullable)
 * @param fromHook  True if generated by an extension, false/null if pi-generated
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record BranchSummaryEntry<T>(
        @JsonProperty("type") String type,
        @JsonProperty("id") String id,
        @JsonProperty("parentId") String parentId,
        @JsonProperty("timestamp") String timestamp,
        @JsonProperty("fromId") String fromId,
        @JsonProperty("summary") String summary,
        @JsonProperty("details") T details,
        @JsonProperty("fromHook") Boolean fromHook
) implements SessionEntry {

    /**
     * Creates a new branch summary entry.
     *
     * @param id        Unique entry identifier
     * @param parentId  Parent entry ID
     * @param timestamp ISO 8601 timestamp
     * @param fromId    ID of the branch start entry
     * @param summary   The branch summary
     * @param details   Extension-specific details (nullable)
     * @param fromHook  Whether generated by extension
     * @param <T>       Type of details
     * @return A new BranchSummaryEntry
     */
    public static <T> BranchSummaryEntry<T> create(
            String id,
            String parentId,
            String timestamp,
            String fromId,
            String summary,
            T details,
            Boolean fromHook
    ) {
        return new BranchSummaryEntry<>("branch_summary", id, parentId, timestamp, fromId, summary, details, fromHook);
    }

    /**
     * Creates a new branch summary entry without extension details.
     *
     * @param id        Unique entry identifier
     * @param parentId  Parent entry ID
     * @param timestamp ISO 8601 timestamp
     * @param fromId    ID of the branch start entry
     * @param summary   The branch summary
     * @return A new BranchSummaryEntry
     */
    public static BranchSummaryEntry<Void> create(
            String id,
            String parentId,
            String timestamp,
            String fromId,
            String summary
    ) {
        return create(id, parentId, timestamp, fromId, summary, null, null);
    }
}
