package com.pi.coding.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Session entry recording a compaction operation.
 *
 * <p>When the conversation becomes too long, older messages are summarized
 * into a compaction entry. The summary replaces the compacted messages in
 * the LLM context, while the original messages remain in the session file.
 *
 * <p><b>Validates: Requirement 1.6</b>
 *
 * @param <T>              Type of extension-specific details
 * @param type             Always "compaction"
 * @param id               Unique entry identifier
 * @param parentId         Parent entry ID (null for first entry)
 * @param timestamp        ISO 8601 timestamp
 * @param summary          The generated summary of compacted messages
 * @param firstKeptEntryId ID of the first entry kept after compaction
 * @param tokensBefore     Token count before compaction
 * @param details          Extension-specific data (nullable)
 * @param fromHook         True if generated by an extension, false/null if pi-generated
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CompactionEntry<T>(
        @JsonProperty("type") String type,
        @JsonProperty("id") String id,
        @JsonProperty("parentId") String parentId,
        @JsonProperty("timestamp") String timestamp,
        @JsonProperty("summary") String summary,
        @JsonProperty("firstKeptEntryId") String firstKeptEntryId,
        @JsonProperty("tokensBefore") int tokensBefore,
        @JsonProperty("details") T details,
        @JsonProperty("fromHook") Boolean fromHook
) implements SessionEntry {

    /**
     * Creates a new compaction entry.
     *
     * @param id               Unique entry identifier
     * @param parentId         Parent entry ID
     * @param timestamp        ISO 8601 timestamp
     * @param summary          The compaction summary
     * @param firstKeptEntryId ID of first kept entry
     * @param tokensBefore     Token count before compaction
     * @param details          Extension-specific details (nullable)
     * @param fromHook         Whether generated by extension
     * @param <T>              Type of details
     * @return A new CompactionEntry
     */
    public static <T> CompactionEntry<T> create(
            String id,
            String parentId,
            String timestamp,
            String summary,
            String firstKeptEntryId,
            int tokensBefore,
            T details,
            Boolean fromHook
    ) {
        return new CompactionEntry<>("compaction", id, parentId, timestamp, summary, firstKeptEntryId, tokensBefore, details, fromHook);
    }

    /**
     * Creates a new compaction entry without extension details.
     *
     * @param id               Unique entry identifier
     * @param parentId         Parent entry ID
     * @param timestamp        ISO 8601 timestamp
     * @param summary          The compaction summary
     * @param firstKeptEntryId ID of first kept entry
     * @param tokensBefore     Token count before compaction
     * @return A new CompactionEntry
     */
    public static CompactionEntry<Void> create(
            String id,
            String parentId,
            String timestamp,
            String summary,
            String firstKeptEntryId,
            int tokensBefore
    ) {
        return create(id, parentId, timestamp, summary, firstKeptEntryId, tokensBefore, null, null);
    }
}
